heroku:
  adapter:  sqlite3
  host:     localhost
  database: db/saaskit_development.sqlite3
  pool:     5
  username: saaskit

development:
  adapter:  sqlite3
  host:     localhost
  database: db/saaskit_development.sqlite3
  pool:     5
  username: saaskit

staging:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: saaskit_development
  pool:     5
  username: saaskit
  password: saaskit
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: saaskit_test
  pool:     5
  username: saaskit
  password: saaskit
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: saaskit_production
  pool:     5
  username: saaskit
  password: saaskit
  template: template0
