heroku:
  adapter:  sqlite3
  host:     localhost
  database: db/saaskit_heroku.sqlite3
  pool:     5
  username: saaskit

development:
  adapter:  sqlite3
  host:     localhost
  database: db/saaskit_development.sqlite3
  pool:     5
  username: saaskit

test:
  adapter:  sqlite3
  host:     localhost
  database: db/saaskit_test.sqlite3
  pool:     5
  username: saaskit
